export const PRODUCT_CATEGORY_OPTIONS = [
  { value: 'prescription', label: 'Prescription Drugs' },
  { value: 'otc', label: 'Over-the-Counter (OTC)' },
  { value: 'vitamins', label: 'Vitamins & Supplements' },
  { value: 'medical-devices', label: 'Medical Devices' },
  { value: 'personal-care', label: 'Personal Care' },
  { value: 'baby-care', label: 'Baby & Child Care' },
  { value: 'first-aid', label: 'First Aid' },
  { value: 'diabetic-care', label: 'Diabetic Care' },
  { value: 'cosmetics', label: 'Cosmetics' },
  { value: 'laboratory', label: 'Laboratory' },
  { value: 'surgical', label: 'Surgical' },
  { value: 'dental', label: 'Dental' },
  { value: 'other', label: 'Other' },
] as const;

export const PRODUCT_UNIT_OPTIONS = [
  { value: 'tablet', label: 'Tablet (Single loose pill)' },
  { value: 'capsule', label: 'Capsule (Single loose capsule)' },
  { value: 'card', label: 'Card (Blister Card — sold per card)' },
  { value: 'bottle', label: 'Bottle (Syrup, Suspension, Drops)' },
  { value: 'vial', label: 'Vial' },
  { value: 'ampoule', label: 'Ampoule' },
  { value: 'sachet', label: 'Sachet' },
  { value: 'tube', label: 'Tube' },
  { value: 'jar', label: 'Jar' },
  { value: 'box', label: 'Box' },
  { value: 'pack', label: 'Pack' },
  { value: 'strip', label: 'Test Strip (Rapid Diagnostic / Glucose / Malaria)' },
  { value: 'syringe', label: 'Syringe' },
  { value: 'kit', label: 'Kit' },
  { value: 'roll', label: 'Roll' },
  { value: 'piece', label: 'Piece' },
  { value: 'ml', label: 'Milliliter (ml)' },
  { value: 'mg', label: 'Milligram (mg)' },
  { value: 'g', label: 'Gram (g)' },
] as const;

export const PACK_TYPE_OPTIONS = [
  { value: 'Card', label: 'Card (Blister Card)' },
  { value: 'Box', label: 'Box' },
  { value: 'Carton', label: 'Carton / Outer' },
  { value: 'Pack', label: 'Pack' },
  { value: 'Blister', label: 'Blister Pack' },
  { value: 'Bottle', label: 'Bottle' },
  { value: 'Sachet', label: 'Sachet' },
  { value: 'Tube', label: 'Tube' },
  { value: 'Vial', label: 'Vial' },
  { value: 'Ampoule', label: 'Ampoule' },
  { value: 'Strip', label: 'Test Strip (RDT)' },
  { value: 'Kit', label: 'Kit' },
  { value: 'Roll', label: 'Roll' },
] as const;

